#!/bin/bash
set -e

# Чіткі шляхи для cookies
HOSTPATH_COOKIES="/app/ytdl-cookies.txt"
TMP_COOKIES="/tmp/ytdl-cookies.txt"

echo "🔍 Checking for cookies sources..."

# Видаляємо старий /tmp/ytdl-cookies.txt якщо він застарілий
if [ -f "$TMP_COOKIES" ]; then
    echo "🗑️  Removing old $TMP_COOKIES..."
    rm -f "$TMP_COOKIES"
fi

# Копіюємо та конвертуємо cookies з /app/ytdl-cookies.txt (hostPath)
if [ -f "$HOSTPATH_COOKIES" ]; then
    echo "📋 Found cookies at $HOSTPATH_COOKIES"
    COOKIE_SIZE=$(stat -f%z "$HOSTPATH_COOKIES" 2>/dev/null || stat -c%s "$HOSTPATH_COOKIES" 2>/dev/null)
    echo "📦 Cookie file size: $COOKIE_SIZE bytes"
    
    if [ "$COOKIE_SIZE" -gt 100 ]; then
        echo "✅ Copying and fixing cookies to $TMP_COOKIES..."
        
        # Конвертуємо cookies в правильний Netscape формат
        python3 - <<'EOF'
import re
import sys

def fix_cookies(input_file, output_file):
    """Конвертує cookies в правильний Netscape формат"""
    
    with open(input_file, 'r') as f:
        content = f.read()
    
    fixed_lines = []
    fixed_lines.append("# Netscape HTTP Cookie File\n")
    fixed_lines.append("# This file was generated by entrypoint.sh\n")
    
    for line in content.split('\n'):
        line = line.strip()
        
        # Skip empty lines and comments
        if not line or line.startswith('#'):
            continue
        
        # Розбиваємо по табуляції або множинних пробілах
        parts = re.split(r'\t+|\s{2,}', line)
        
        # Мінімум 6 полів: domain, flag, path, secure, expiration, name
        # Value опціональний (може бути порожнім)
        if len(parts) >= 6:
            domain = parts[0]
            flag = parts[1] if parts[1] in ['TRUE', 'FALSE'] else 'TRUE'
            path = parts[2]
            secure = parts[3] if parts[3] in ['TRUE', 'FALSE'] else 'FALSE'
            expiration = parts[4]
            name = parts[5]
            # Value може бути відсутнім (для тестових cookies)
            if len(parts) > 6:
                value = '\t'.join(parts[6:]) if len(parts) > 7 else parts[6]
            else:
                value = ''  # Порожнє значення для тестових cookies
            
            # Видаляємо \n з кінця value якщо є
            value = value.rstrip('\n')
            
            # Формуємо правильний рядок
            fixed_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            fixed_lines.append(fixed_line)
    
    with open(output_file, 'w') as f:
        f.writelines(fixed_lines)
    
    print(f"✅ Fixed {len(fixed_lines) - 2} cookies")

fix_cookies('/app/ytdl-cookies.txt', '/tmp/ytdl-cookies.txt')
EOF
        
        chmod 644 "$TMP_COOKIES"
        echo "✅ Cookies fixed and copied successfully"
    else
        echo "⚠️  Warning: Cookie file is too small ($COOKIE_SIZE bytes), might be empty"
    fi
else
    echo "⚠️  Warning: /app/ytdl-cookies.txt not found"
    echo "   Bot will work without cookies - some platforms may have limitations"
    echo "   Ensure /var/www/ytdl-cookies.txt exists on host and is mounted correctly"
fi

# Показуємо фінальний стан cookies
if [ -f "$TMP_COOKIES" ]; then
    FINAL_SIZE=$(stat -f%z "$TMP_COOKIES" 2>/dev/null || stat -c%s "$TMP_COOKIES" 2>/dev/null)
    COOKIE_COUNT=$(grep -v '^#' "$TMP_COOKIES" | grep -v '^$' | wc -l)
    echo "📊 Final cookies status: $COOKIE_COUNT cookies, $FINAL_SIZE bytes"
else
    echo "❌ No cookies available - bot will run with limited functionality"
fi

# Перевірка Node.js для yt-dlp JavaScript challenges
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    NODE_PATH=$(which node)
    echo "✅ Node.js detected: $NODE_VERSION at $NODE_PATH"
    
    # Переконуємось що Node.js в PATH
    export PATH="/usr/bin:$PATH"
    
    # Тест JavaScript execution
    if node -e "console.log('JS OK')" &> /dev/null; then
        echo "✅ Node.js JavaScript execution works"
    else
        echo "⚠️  Node.js found but JS execution failed"
    fi
else
    echo "⚠️  Warning: Node.js not found - YouTube signature solving may fail"
fi

# Запускаємо основний процес
echo "🚀 Starting YouTube Downloader Bot..."
exec python app.py
