#!/usr/bin/env python3
"""
Конвертує cookies з неправильного формату в Netscape формат
"""

import sys
import re

def fix_cookies(input_file, output_file):
    """Конвертує cookies в правильний Netscape формат"""
    
    with open(input_file, 'r') as f:
        content = f.read()
    
    fixed_lines = []
    fixed_lines.append("# Netscape HTTP Cookie File\n")
    fixed_lines.append("# This file was generated by fix_cookies.py\n")
    
    for line in content.split('\n'):
        line = line.strip()
        
        # Skip empty lines and comments
        if not line or line.startswith('#'):
            continue
        
        # Parse cookies - формат: domain\tTRUE\t/\tTRUE\texpiration\tname\tvalue
        # Але у вас все в одному рядку з пробілами
        
        # Розбиваємо по табуляції або множинних пробілах
        parts = re.split(r'\t+|\s{2,}', line)
        
        if len(parts) >= 7:
            domain = parts[0]
            flag = parts[1] if parts[1] in ['TRUE', 'FALSE'] else 'TRUE'
            path = parts[2]
            secure = parts[3] if parts[3] in ['TRUE', 'FALSE'] else 'FALSE'
            expiration = parts[4]
            name = parts[5]
            # Value може містити пробіли, тому беремо все що залишилось
            value = '\t'.join(parts[6:]) if len(parts) > 7 else parts[6]
            
            # Видаляємо \n з кінця value якщо є
            value = value.rstrip('\n')
            
            # Формуємо правильний рядок
            fixed_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            fixed_lines.append(fixed_line)
            print(f"✅ Fixed: {name}")
        else:
            print(f"⚠️  Skipped invalid line: {line[:50]}...")
    
    with open(output_file, 'w') as f:
        f.writelines(fixed_lines)
    
    print(f"\n✅ Fixed {len(fixed_lines) - 2} cookies")
    print(f"📝 Output: {output_file}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python fix_cookies.py <input_file> <output_file>")
        print("Example: python fix_cookies.py /tmp/cookies.txt /tmp/cookies_fixed.txt")
        sys.exit(1)
    
    fix_cookies(sys.argv[1], sys.argv[2])
